apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mb9gs9p1g-java-springboot
  janus-idp.io/tekton: mb9gs9p1g-java-springboot
  backstage.io/kubernetes-id: mb9gs9p1g-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mb9gs9p1g-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
